### ISSUE TITLE
cannot open the website

### ISSUE THREAD

**Issue by Xiaozhuangzhuang** [facebookincubator/spectrum#195]
why i cannot open the website to learn this project?

**Comment by AurelC2G** [comment]
Fixed, thank you for the report!

**Comment by Xiaozhuangzhuang** [comment]
https://libspectrum.io  still cannot be reached with a ERR_NAME_RESOLUTION_FAILED error.

**Comment by AurelC2G** [comment]
Works for me, and also according to https://www.isitdownrightnow.com/libspectrum.io.html

On the other hand, it looks like it may be blocked in China? (according to https://www.comparitech.com/privacy-security-tools/blockedinchina/)
Is this where you are trying to access the website from?
